language: python
python: '3.8'
cache:
  pip: true
  directories:
    - node_modules

# Use container-based infrastructure
dist: focal
sudo: false

# Services
services:
  - postgresql

addons:
  postgresql: '9.6'

env:
  global:
    - DJANGO_SETTINGS_MODULE=tbx.settings.production
    - DATABASE_URL=postgres://postgres@localhost/test_db
    - CFG_SECRET_KEY=iamnotsosecret
    - CFG_ALLOWED_HOSTS=localhost

before_script:
  # Create a database
  - psql -c 'create database test_db;' -U postgres

install:
  - wget https://raw.githubusercontent.com/python-poetry/poetry/1.1.1/get-poetry.py
  - echo "eedf0fe5a31e5bb899efa581cbe4df59af02ea5f get-poetry.py" | sha1sum -c
  - python get-poetry.py
  - rm get-poetry.py
  - poetry config virtualenvs.create false
  - poetry install --extras flake8 isort

script:
  # Code style, missing imports, etc
  - flake8 tbx
  - isort --check-only --diff --recursive tbx

  # Run system checks
  - python manage.py check

  # Check for missing migrations
  - python manage.py makemigrations --check

  # Run tests
  - python manage.py test
