context:
  page:
    title: Service
    get_verbose_name: service
    hero:
      title: The digital product agency <span>for tomorrow’s nonprofits</span>.
      in_page_nav:
        - { title: Services, href: services }
        - { title: Clients, href: clients }
        - { title: Thinking, href: thinking }
    clients:
      - { title: Samaritans }
      - { title: Samaritans }
      - { title: Samaritans }
      - { title: Samaritans }
      - { title: Samaritans }
    casestudies:
      - {
          title: We’ve launched a supporter-centred Wagtail website for Oxfam GB,
          client: Oxfam,
          desc: Following the launch of a new public engagement strategy Oxfam needed a website to ‘make it happen’ by reshaping and tailoring the entire experience to the needs of Oxfam’s supporters.,
        }
      - {
          title: We’ve launched a supporter-centred Wagtail website for Oxfam GB,
          client: Oxfam,
          desc: Following the launch of a new public engagement strategy Oxfam needed a website to ‘make it happen’ by reshaping and tailoring the entire experience to the needs of Oxfam’s supporters.,
        }
      - {
          title: We’ve launched a supporter-centred Wagtail website for Oxfam GB,
          client: Oxfam,
          desc: Following the launch of a new public engagement strategy Oxfam needed a website to ‘make it happen’ by reshaping and tailoring the entire experience to the needs of Oxfam’s supporters.,
        }
      - {
          title: We’ve launched a supporter-centred Wagtail website for Oxfam GB,
          client: Oxfam,
          desc: Following the launch of a new public engagement strategy Oxfam needed a website to ‘make it happen’ by reshaping and tailoring the entire experience to the needs of Oxfam’s supporters.,
        }
  see_more:
    text: See more casestudies
    href: '/work'
